version: "3.9"

services:
  backend:
    build:
      context: ./back
    container_name: backendV2
    volumes:
      - ./properties_data:/app/properties_data
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./react-ts
    container_name: frontendV2
    ports:
      - "3000:80"
    depends_on:
      - backend
